version: "3.9"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - medical_platform_media_data:/app/media
      - medical_platform_static_data:/app/staticfiles
    depends_on:
      - project_db
      - redis
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: project_db
      POSTGRES_PORT: 5432
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}

  project_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - medical_platform_postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    restart: always


  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - medical_platform_static_data:/app/staticfiles:ro
      - medical_platform_media_data:/app/media:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web


volumes:
  medical_platform_postgres_data:
    external: true
  medical_platform_media_data:
    external: true
  medical_platform_static_data:
    external: true
